### ISSUE TITLE
The Wallets are not being retrieved either via iOS or android

### ISSUE THREAD

**Issue by seanwestfall** [WalletConnect/Web3ModalFlutter#43]
**Describe the bug**
The wallet icons are not being generated for some reason, after selecting the network:
![gdh7G6A](https://github.com/WalletConnect/Web3ModalFlutter/assets/9439906/d6357000-ecff-464b-869b-9ff3a538ddb5)

**To Reproduce**
1. Build, and launch the app, on either iOS, or android, emulator or native.
2. Click on select the network, and pick a network.
3. Then it will switch to the select a wallet screen, and it will all be blank.

**Expected behavior**

**Screenshots**
![gdh7G6A](https://github.com/WalletConnect/Web3ModalFlutter/assets/9439906/d6357000-ecff-464b-869b-9ff3a538ddb5)

**Desktop (please complete the following information):**
 - OS: NA
 - Browser: NA
 - Version: NA

**Smartphone (please complete the following information):**
 - Device: [iPhone 6.2.2]
 - OS: [iOS, android]
 - Browser NA
 - Version [3.0.0-beta06]

**Additional context**
This is the stack trace from the iOS emulator:
```
2023-10-21 23:28:41.694144-0700 Runner[3144:41620] flutter: \^[[38;5;196m│ ⛔ [ExplorerService] Error fetching native apps data<…>
2023-10-21 23:28:41.694723-0700 Runner[3144:41620] flutter: \^[[38;5;196m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
2023-10-21 23:28:41.700775-0700 Runner[3144:41620] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Exception: FormatException: Unexpected character (at character 1)
Forbidden
^

#0      ExplorerService._fetchNativeAppData (package:web3modal_flutter/services/explorer_service/explorer_service.dart:163:7)
<asynchronous suspension>
#1      ExplorerService._fetchInstalledListings (package:web3modal_flutter/services/explorer_service/explorer_service.dart:168:30)
<asynchronous suspension>
#2      ExplorerService.init (package:web3modal_flutter/services/explorer_service/explorer_service.dart:84:26)
<asynchronous suspension>
```

and this is the stack trace from the android emulator:
```
E/flutter: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: FormatException: Unexpected character (at character 1)
    Forbidden
    ^
    
    #0      ExplorerService._fetchNativeAppData (package:web3modal_flutter/services/explorer_service/explorer_service.dart:163:7)
    <asynchronous suspension>
    #1      ExplorerService._fetchInstalledListings (package:web3modal_flutter/services/explorer_service/explorer_service.dart:168:30)
    <asynchronous suspension>
    #2      ExplorerService.init (package:web3modal_flutter/services/explorer_service/explorer_service.dart:84:26)
    <asynchronous suspension>
```

**Comment by quetool** [comment]
Hello @seanwestfall! Have you passed a projectId or a web3app object to W3MService? https://docs.walletconnect.com/web3modal/flutter/options

**Comment by seanwestfall** [comment]
@quetool that was it!
I had to hard code the projectid into `/example/lib/home_page.dart` in order for it to work. I hope this helps somebody else out there.

```dart
void _initialize() async {
    _web3App = Web3App(
      core: Core(projectId: '...1234...'),
      metadata: const PairingMetadata(
        name: 'Web3Modal Flutter Example',
        description: 'Web3Modal Flutter Example',
        url: 'https://www.walletconnect.com/',
        icons: ['https://walletconnect.com/walletconnect-logo.png'],
        redirect: Redirect(
          native: 'flutterdapp://',
          universal: 'https://www.walletconnect.com',
        ),
      ),
    );
```

**Comment by quetool** [comment]
Hello @seanwestfall, that is how it has to be done indeed. As mentioned in the docs you can do this

```
final _web3App = await Web3App.createInstance(
  projectId: '{YOUR_PROJECT_ID}',
  metadata: const PairingMetadata(
    name: 'Web3Modal Flutter Example',
    description: 'Web3Modal Flutter Example',
    url: 'https://www.walletconnect.com/',
    icons: ['https://walletconnect.com/walletconnect-logo.png'],
    redirect: Redirect(
      native: 'flutterdapp://',
      universal: 'https://www.walletconnect.com',
    ),
  ),
);

// Register callbacks on the Web3App you'd like to use

final _w3mService = W3MService(web3App: _web3App);
```

If you don't want to hardcode the projectId you can pass it through --dart-defines or environment variables.
